# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/projet2_raph_oumou/projet2_raph_oumou.cache/wt} [current_project]
set_property parent.project_path {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/projet2_raph_oumou/projet2_raph_oumou.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {c:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/projet2_raph_oumou/projet2_raph_oumou.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/projet2_raph_oumou/projet2_raph_oumou.srcs/sources_1/imports/Sources/cnt.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/dbnc.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/meta_harden.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/msa_display.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/msa_simon.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/prbs7.vhd}
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/delay_cnt.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/heartbeat.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/lumi.vhd}
  {C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/projet2_raph_oumou/projet2_raph_oumou.srcs/sources_1/imports/rtl/simon_affichage_del.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/timing.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/HP EliteBook Pro/Documents/GitHub/ELE3311_Projet2/Sources/timing.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top simon_affichage_del -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef simon_affichage_del.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file simon_affichage_del_utilization_synth.rpt -pb simon_affichage_del_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
